;; -*- mode: eask; lexical-binding: t -*-

(package "orgzly-formatter"
         "0.1.0"
         "Orgzly-compatible blank-line formatter for org-mode")

(website-url "https://github.com/stfl/orgzly-formatter")
(keywords "outlines" "convenience" "files")

(source "melpa")

(depends-on "emacs" "27.1")

(package-file "orgzly-formatter.el")

(files "orgzly-formatter.el")

(script "test" "eask test ert orgzly-formatter-test.el")
